// <auto-generated />
using System;
using Dotnet_Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotnetProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240125190408_init-database")]
    partial class initdatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dotnet_Project.Models.Lobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFull")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("Dotnet_Project.Models.Player", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<int?>("LinkedLobbyId")
                        .HasColumnType("int");

                    b.Property<int?>("LobbyId")
                        .HasColumnType("int");

                    b.Property<int?>("LobbyId1")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamNumber")
                        .HasColumnType("int");

                    b.Property<string>("mdp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("number_draws")
                        .HasColumnType("int");

                    b.Property<int>("number_losses")
                        .HasColumnType("int");

                    b.Property<int>("number_wins")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LinkedLobbyId");

                    b.HasIndex("LobbyId");

                    b.HasIndex("LobbyId1");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            EMail = "player1@example.com",
                            IsAdmin = false,
                            Name = "Ala",
                            PhotoPath = "path1",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password1",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 2,
                            EMail = "player2@example.com",
                            IsAdmin = false,
                            Name = "Taher",
                            PhotoPath = "path2",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password2",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 3,
                            EMail = "player3@example.com",
                            IsAdmin = false,
                            Name = "Habib",
                            PhotoPath = "path2",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password3",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 4,
                            EMail = "player4@example.com",
                            IsAdmin = false,
                            Name = "Fedy",
                            PhotoPath = "path2",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password4",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 5,
                            EMail = "player5@example.com",
                            IsAdmin = false,
                            Name = "Najar",
                            PhotoPath = "path2",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password5",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 6,
                            EMail = "player6@example.com",
                            IsAdmin = false,
                            Name = "Reb3i",
                            PhotoPath = "path2",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password5",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 7,
                            EMail = "player7@example.com",
                            IsAdmin = false,
                            Name = "Ghazi",
                            PhotoPath = "path2",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password5",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 8,
                            EMail = "player8@example.com",
                            IsAdmin = false,
                            Name = "Kamel",
                            PhotoPath = "path2",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password5",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 9,
                            EMail = "player9@example.com",
                            IsAdmin = false,
                            Name = "Karim",
                            PhotoPath = "path2",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password5",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 10,
                            EMail = "play10@example.com",
                            IsAdmin = false,
                            Name = "Samir",
                            PhotoPath = "path1",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password1",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 11,
                            EMail = "play11@example.com",
                            IsAdmin = false,
                            Name = "Kais",
                            PhotoPath = "path1",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password1",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 12,
                            EMail = "play12@example.com",
                            IsAdmin = false,
                            Name = "Aziz",
                            PhotoPath = "path1",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password1",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 13,
                            EMail = "play13@example.com",
                            IsAdmin = false,
                            Name = "Youssef",
                            PhotoPath = "path1",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password1",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 14,
                            EMail = "play14@example.com",
                            IsAdmin = false,
                            Name = "Hamza",
                            PhotoPath = "path1",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password1",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 15,
                            EMail = "play15@example.com",
                            IsAdmin = false,
                            Name = "Ali",
                            PhotoPath = "path1",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password1",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 16,
                            EMail = "play16@example.com",
                            IsAdmin = false,
                            Name = "Mustafa",
                            PhotoPath = "path1",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password1",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 17,
                            EMail = "play16@example.com",
                            IsAdmin = false,
                            Name = "Elyess",
                            PhotoPath = "path1",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password1",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 18,
                            EMail = "play16@example.com",
                            IsAdmin = false,
                            Name = "Omar",
                            PhotoPath = "path1",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password1",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 19,
                            EMail = "play16@example.com",
                            IsAdmin = false,
                            Name = "Ismail",
                            PhotoPath = "path1",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password1",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 20,
                            EMail = "play16@example.com",
                            IsAdmin = false,
                            Name = "Amine",
                            PhotoPath = "path1",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password1",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 21,
                            EMail = "play16@example.com",
                            IsAdmin = false,
                            Name = "Talel",
                            PhotoPath = "path1",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password1",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        },
                        new
                        {
                            ID = 22,
                            EMail = "play16@example.com",
                            IsAdmin = false,
                            Name = "Chehata",
                            PhotoPath = "path1",
                            Surname = "Doe",
                            TeamNumber = 0,
                            mdp = "password1",
                            numberdraws = 0,
                            numberlosses = 0,
                            numberwins = 0
                        });
                });

            modelBuilder.Entity("Dotnet_Project.Models.Stade_Owner", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StadeId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mdp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("StadeId");

                    b.ToTable("StadeOwners");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            EMail = "owner1@example.com",
                            Name = "Owner1",
                            Surname = "Owner1Surname",
                            mdp = "password1"
                        },
                        new
                        {
                            ID = 2,
                            EMail = "owner2@example.com",
                            Name = "Owner2",
                            Surname = "Owner2Surname",
                            mdp = "password2"
                        });
                });

            modelBuilder.Entity("Dotnet_Project.Models.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Localisation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stadiums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description1",
                            Localisation = "Location1",
                            Name = "Stadium1",
                            PhotoPath = "path1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description2",
                            Localisation = "Location2",
                            Name = "Stadium2",
                            PhotoPath = "path2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description3",
                            Localisation = "Location3",
                            Name = "Stadium3",
                            PhotoPath = "path2"
                        });
                });

            modelBuilder.Entity("Dotnet_Project.Models.Time_Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("StadiumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("end_time")
                        .HasColumnType("datetime2");

                    b.Property<bool>("occupancy")
                        .HasColumnType("bit");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StadiumId");

                    b.ToTable("TimeSlots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StadiumId = 1,
                            endtime = new DateTime(2024, 1, 25, 21, 34, 8, 683, DateTimeKind.Local).AddTicks(2452),
                            occupancy = true,
                            starttime = new DateTime(2024, 1, 25, 20, 4, 8, 683, DateTimeKind.Local).AddTicks(2392)
                        },
                        new
                        {
                            Id = 2,
                            StadiumId = 2,
                            endtime = new DateTime(2024, 1, 25, 21, 34, 8, 683, DateTimeKind.Local).AddTicks(2461),
                            occupancy = false,
                            starttime = new DateTime(2024, 1, 25, 20, 4, 8, 683, DateTimeKind.Local).AddTicks(2459)
                        },
                        new
                        {
                            Id = 3,
                            StadiumId = 3,
                            endtime = new DateTime(2024, 1, 25, 21, 34, 8, 683, DateTimeKind.Local).AddTicks(2465),
                            occupancy = false,
                            starttime = new DateTime(2024, 1, 25, 20, 4, 8, 683, DateTimeKind.Local).AddTicks(2464)
                        },
                        new
                        {
                            Id = 4,
                            StadiumId = 1,
                            endtime = new DateTime(2024, 1, 25, 23, 34, 8, 683, DateTimeKind.Local).AddTicks(2469),
                            occupancy = false,
                            starttime = new DateTime(2024, 1, 25, 22, 4, 8, 683, DateTimeKind.Local).AddTicks(2468)
                        },
                        new
                        {
                            Id = 5,
                            StadiumId = 2,
                            endtime = new DateTime(2024, 1, 25, 23, 34, 8, 683, DateTimeKind.Local).AddTicks(2473),
                            occupancy = false,
                            starttime = new DateTime(2024, 1, 25, 22, 4, 8, 683, DateTimeKind.Local).AddTicks(2472)
                        },
                        new
                        {
                            Id = 6,
                            StadiumId = 3,
                            endtime = new DateTime(2024, 1, 25, 23, 34, 8, 683, DateTimeKind.Local).AddTicks(2477),
                            occupancy = false,
                            starttime = new DateTime(2024, 1, 25, 22, 4, 8, 683, DateTimeKind.Local).AddTicks(2476)
                        });
                });

            modelBuilder.Entity("Dotnet_Project.Models.Lobby", b =>
                {
                    b.HasOne("Dotnet_Project.Models.Time_Slot", "TimeSlot")
                        .WithMany("LinkedLobbies")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("Dotnet_Project.Models.Player", b =>
                {
                    b.HasOne("Dotnet_Project.Models.Lobby", "LinkedLobby")
                        .WithMany("Players")
                        .HasForeignKey("LinkedLobbyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dotnet_Project.Models.Lobby", null)
                        .WithMany("Team1")
                        .HasForeignKey("LobbyId");

                    b.HasOne("Dotnet_Project.Models.Lobby", null)
                        .WithMany("Team2")
                        .HasForeignKey("LobbyId1");

                    b.Navigation("LinkedLobby");
                });

            modelBuilder.Entity("Dotnet_Project.Models.Stade_Owner", b =>
                {
                    b.HasOne("Dotnet_Project.Models.Stadium", "stade")
                        .WithMany()
                        .HasForeignKey("StadeId");

                    b.Navigation("stade");
                });

            modelBuilder.Entity("Dotnet_Project.Models.Time_Slot", b =>
                {
                    b.HasOne("Dotnet_Project.Models.Stadium", "stadium")
                        .WithMany("Times")
                        .HasForeignKey("StadiumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("stadium");
                });

            modelBuilder.Entity("Dotnet_Project.Models.Lobby", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Team1");

                    b.Navigation("Team2");
                });

            modelBuilder.Entity("Dotnet_Project.Models.Stadium", b =>
                {
                    b.Navigation("Times");
                });

            modelBuilder.Entity("Dotnet_Project.Models.Time_Slot", b =>
                {
                    b.Navigation("LinkedLobbies");
                });
#pragma warning restore 612, 618
        }
    }
}
